In [30]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("control_group.csv")
df

    person_id  recovery_time_hrs
0        C001                4.4
1        C002                4.1
2        C003                3.2
3        C004                4.3
4        C005                4.9
..        ...                ...
125      C126                3.9
126      C127                3.8
127      C128                4.2
128      C129                4.3
129      C130                4.2

[130 rows x 2 columns]

In [3]:
df.shape

(130, 2)

In [4]:
n1 = 130

In [29]:
m1 = df.recovery_time_hrs.mean().round(2)
m1

np.float64(3.91)

In [24]:
std1 = df.recovery_time_hrs.std().round(2)
std1

np.float64(0.32)

In [26]:
df_test = pd.read_csv("test_group.csv")
df_test

   person_id  recovery_time_hrs
0       T001                3.7
1       T002                4.1
2       T003                3.7
3       T004                3.9
4       T005                3.7
..       ...                ...
95      T096                3.9
96      T097                3.9
97      T098                4.9
98      T099                3.7
99      T100                3.8

[100 rows x 2 columns]

In [14]:
df_test.shape

(100, 2)

In [15]:
n2 = 100

In [27]:
m2 = df_test.recovery_time_hrs.mean().round(2)
m2

np.float64(3.91)

In [31]:
std2 = df_test.recovery_time_hrs.std().round(2)
std2

np.float64(0.32)

In [36]:
a = std1**2/n1
b = std2**2/n2

a,b

(np.float64(0.0007876923076923077), np.float64(0.001024))

In [38]:
z_score = (m1-m2)/np.sqrt(a+b)
z_score

np.float64(0.0)